### ISSUE TITLE
[CACHE BUG]

### ISSUE THREAD

**Issue by threatman68** [Brhsoftco/PlexDL-MetroSet_UI#3]
**Describe the bug**
When connecting to a server after a fresh install of PlexDL, it claims that it cannot read the cache. This shouldn't be an issue since it is a brand new install.

**To Reproduce**
1. Go to PlexDL
2. Load your profile
3. Attempt to Connect to the Server

**Expected behavior**
I expected it to connect me to the server and work like normal.

**Screenshots**
Visit this link to see screenshot:
https://user-images.githubusercontent.com/62534756/77610686-1f92f880-6f6f-11ea-8578-567121cb257b.png

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - OS Version: 10.0.18363 Build 18363

 - Player feature used: N/A
 - PlexDL Metroset_UI Version 1.3.91

**Comment by Brhsoftco** [comment]
Hi there,
Thanks for letting me know. This is an ongoing issue with PlexDL, and it occurs when you have multiple instances of PlexDL open, or another program is trying to scan the content. To temporarily get around this problem, you can use File->Settings->Cache Settings->Mode->Server Caching->False. After doing this, PlexDL will always re-download server lists, which is not optimal, but it is being worked on.

The current solution that has been decided upon (and is being implemented) is defaulting to downloading if caching doesn't work, but since this is intensive with the existing logic, it may take a little while. It is estimated that may take 1-2 weeks for a viable binary release.

**Comment by Brhsoftco** [comment]
A quick note after close: Commonly antivirus software tries to scan cache files since they're hashed.
